### ISSUE TITLE
teleport to position

### ISSUE THREAD

**Issue by loko06320** [RyUkApples/AdminMenu-LaLife#2]
Hello, thanks for your script , i have a question ,

how to use teleport to coordonate ? 

i enter texte like this :  -1250.555 -98.555 -78.200 
what is wrong?

Thx

**Comment by RyUkApples** [comment]
This menu is obsolete. I work on an other project like to DarkRP gamemode on gMod :) https://github.com/RyUkApples/DarkRP And an admin menu is coming
